#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <string.h>
#include <errno.h>

#include <rave.h>

#define err(fmt, ...) fprintf(stderr, fmt, ##__VA_ARGS__)

static int _read_mem(unsigned int from, unsigned int to, unsigned int offset,
	void **mem)
{
	FILE *fmem = fopen("/proc/self/mem", "r");
	int rc = 0;

	if (NULL == fmem) {
		err("Couldn't open proc mem\n");
		return -1;
	}

	*mem = malloc(to - from);
	if (NULL == *mem) {
		err("no mem\n");
		rc = -1;
		goto out;
	}

	rc = fseek(fmem, from, SEEK_SET);
	if (rc) {
		err("Coudn't fseek\n");
		rc = -1;
		goto out;
	}

	printf("Reading region %x-%x\n", from, to);
	fflush(stdout);
	rc = fread(*mem, 1, to - from, fmem);
	if (rc != to - from) {
		err("Bad fread: %s\n", strerror(errno));
		rc = -1;
		goto out;
	}

	printf("Read %d pages from mapped code segment\n", (to - from) / 4096);

out:
	fclose(fmem);
	return rc;
}

static int read_mem(void **mem, size_t *length)
{
	FILE *fmaps = fopen("/proc/self/maps", "r");
	FILE *fexe = fopen("/proc/self/exe", "r");

	unsigned int from, to, offset, major, minor;
	unsigned long inode;
	char flags[4], pathname[256], exe[256];
	ssize_t exe_len;

	int rc = 0;

	if (!fmaps || !fexe) {
		err("Could not open proc fs\n");
		return -1;
	}

	exe_len = readlink("/proc/self/exe", exe, 256);
	if (exe_len == -1) {
		err("Could not readlink\n");
		rc = -1;
		goto out;
	}

	printf("We are %.*s\n", (int)exe_len, exe);

	while (EOF != (rc = fscanf(fmaps, "%x-%x %4s %x %x:%x %lu %256[^\n]s",
		&from, &to, flags, &offset, &major, &minor, &inode, pathname)))
	{
		if (rc != 8) {
			err("fscanf failed\n");
			rc = -1;
			goto out;
		}

		printf("%x-%x %4s %x %x:%x %lu %.*s\n",
			from, to, flags, offset, major, minor, inode, 256, pathname);

		if (strncmp(flags, "r-xp", 4) == 0) {
			if (strncmp(exe, pathname, exe_len) == 0) {
				rc = _read_mem(from, to, offset, mem);
				*length = to - from;
				goto out;
			}
		}
	}

out:
	fclose(fmaps);
	fclose(fexe);
	return rc;
}

/* Tests if the code mapping generated by rave matches what is loaded */
int main(int argc, char **argv) {
	rave_handle_t rh = rave_create();
	void *mem = NULL;
	void *mapping;
	size_t rave_length, self_length;
	int rc;

	rc = rave_init(rh, argv[0]);
	if (rc != 0) {
		err("Init failed\n");
		goto err;
	}

	/* Read the code from /proc/self/mem and compare to the mapping generated by
	 * rave. */
	mapping = rave_get_code(rh, &rave_length);
	if (NULL == mapping) {
		err("No mapping from rave\n");
		goto err;
	}

	rc = read_mem(&mem, &self_length);
	if (rc != 0) {
		err("read mem failed\n");
		goto err;
	}

	if (rave_length != self_length) {
		err("Mismatch length\n");
		goto err;
	}

	/* compare */
	rc = memcmp(mem, mapping, self_length);
	if (rc != 0) {
		err("Bad code data from rave\n");
		goto err;
	}

	printf("Code matches!\n");

	rc = rave_close(rh);
	if (rc != 0) {
		err("Close failed\n");
		goto err;
	}

	rave_destroy(rh);
	if (mem) free(mem);

	printf("Success!\n");
	return EXIT_SUCCESS;
err:
	return EXIT_FAILURE;
}

